version: '3.8'

services:
  backend:
    build: ./backend
    container_name: seotda_backend
    environment:
      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: ""         # 비번 없음
      DB_NAME: poker_db
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: seotda_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: unless-stopped

